### PR TITLE
140 seed data improvements

### PR DESCRIPTION
**Pull request by jakerabid**
https://github.com/WhareHauora/wharehauora-server/issues/140

Made the seed data transactional so if part fails it all fails, which means its rerunnable
Made the seed data check for the before adding the data which also makes it more rerunnable
Added in a bunch of dev/test/staging data for developers so that we can get up and running quickly

### CODE REVIEW

**Comment by Br3nda** [comment]
Looks good. There is also the rake task for making fake readings.

**Comment by jakerabid** [comment]
huh there is too, but I feel like they both kinda do different things though. This bangs in a bunch of fake readings all at once, rather than in real time.

**Comment by Br3nda** [comment]
Another approach is factory girl.

**Comment by jakerabid** [comment]
Factory girl feels like a much more righter approach. This work is still handy, and I'd like to merge it, but perhaps we can use factory girl in the future once things get a bit more complicated?

**Pull request merged**
