### PR TITLE
Fix deletion of sensors

### PR DESCRIPTION
**Pull request by Br3nda**
Fixes crash when an admin attempts to assign a sensor in a house

### CODE REVIEW

**Comment by Br3nda** [comment]
fixes #291

**Comment by Br3nda** [comment]
To test, go to the review app
https://whare-experimental-pr-293.herokuapp.com/
log in as admin@wharehauora.nz / password

go to a home

click admin -> sensors
pick a sensor and delete it.


it used to give an error page

now it should delete and not give any errors

**Comment by Br3nda** [comment]
@kamikazilady leaving this one for you to review

**Comment by Br3nda** [comment]
@amscraig can u be my reviewer on this one? We can leave another for Hīria when she's back online.

**Comment by Kamikazilady** [comment]
Doing now

**Comment by Kamikazilady** [comment]
Done but can't see waffle on phone to put it to done

**Pull request merged**
