### PR TITLE
Feature/admin screens tidy and tested

### PR DESCRIPTION
**Pull request by Br3nda**
started tidying up some of the titles and navigation menus on pages.
(i'm a bit blocked until the other 2 PRs get merged)

### CODE REVIEW

**Comment by Br3nda** [comment]
I think this one can stay. It's a bit messy to pass that variable all the way

**Comment by Br3nda** [comment]
@amscraig do i need adding to a team? heroku says this:
image

**Comment by amscraig** [comment]
@brenda - you've already been invited to be added to the team. Don't think you've accepted the invite.

**Comment by Br3nda** [comment]
@amscraig i'm in the team, but i don’t have permission to do much 
image

**Comment by Br3nda** [comment]
it's saying i'm in the team, but my role is not allowed to make review apps
image

**Pull request merged**
