### PR TITLE
Gateway status

### PR DESCRIPTION
**Pull request by Br3nda**
We have a gateway that hasn't reported any readings from sensor since it went home to it's destination (it was tested before this). We don't have ready access to it. We need a bit more debug to work out what's going on.

This code change adds a gateway table to the database. It's pretty basic for now. When a gateway unit boots up, they all hit a config url to find the address of the MQTT server. They handily also send their firmware version.

We haven't been logging this anywhere useful. This PR adds that recording into useful info to the database. Each time a gateway asks for it's config, we'll record that it did, thus having a record that it is at least able to access http on port 80, and some DNS. It'll help us narrow down faults.

### CODE REVIEW

**Comment by Br3nda** [comment]
Here's what the gateway status page looks like now
image

**Comment by Br3nda** [comment]
@ben-rabid can you accept the invite from your Rabid account, or approve from your personal account? Then i don't need to run off branch restrictions so I can merge this.

**Comment by ben-rabid** [comment]
@Br3nda I accepted the invite a while back - I think I need adding to the SensorDevs group from this account

**Comment by ben-rabid** [comment]
There we go - good to merge @Br3nda

**Pull request merged**
