### PR TITLE
the controllers support have a param "since" which describes how many…

### PR DESCRIPTION
**Pull request by jakerabid**
… days ago to show the data for. There is no UI support for modifying this number yet though

### CODE REVIEW

**Comment by Br3nda** [comment]
works as described. Is this WIP? tests and UI needed. Shall we leave this PR unmerged for now?

**Comment by jakerabid** [comment]
Yeah, it does need tests and UI - I was gonna do them next.

**Comment by Br3nda** [comment]
After merging master in, we now have `app/controllers/homes_controller.rb:11:3: C: Assignment Branch Condition size for show is too high. [18.06/15]`

**Comment by jakerabid** [comment]
@Br3nda I changed some stuff, now the checks pass, and the UI is functional.

**Pull request merged**
