### PR TITLE
Adding filters

### PR DESCRIPTION
**Pull request by Br3nda**
More filters to use on the API

### CODE REVIEW

**Comment by Br3nda** [comment]
@MeghanHughes can you see the pattern here? if there's more filters needed that the server doesn't provide you can add them in a PR.

**Comment by MeghanHughes** [comment]
Hey @Br3nda can we add @anna-marie-vos to this repo so she can see the PRs too?

**Comment by Br3nda** [comment]
Okay -- but where do you need her added? It's all public and open source so she can see them already.

**Comment by Br3nda** [comment]
I've sent her an invite to the organisation

**Pull request merged**
